// <auto-generated />
namespace Todos.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddTodo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTodo));
        
        string IMigrationMetadata.Id
        {
            get { return "201212140201210_AddTodo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
